services:
  app-2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-2
    image: base-2
    volumes:
      - ./:/var/www
    ports:
      - "8002:8002"
    networks:
      - shared-net

  nginx-2:
    image: nginx:alpine
    container_name: nginx-2
    ports:
      - "8082:8082"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shared-net

networks:
  shared-net:
    external: true
